[package]
name = "rust-rest-api"
version = "0.1.0"
edition = "2024"

[alias]
dev = "watch -c -w src/ -w Cargo.toml -x check -x run"

[dependencies]
axum = "0.8.4"
chrono = "0.4.41"
mongodb = "3.3.0"
serde = "1.0.219"
serde_json = "1.0.143"
thiserror = "2.0.16"
tokio = "1.47.1"
